name: buro_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.6
  path_provider: ^2.0.11
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  intl: ^0.17.0
  flutter_bloc: ^8.1.4
  http: ^1.2.1
  get_it: ^7.6.7
  cached_network_image: ^3.4.1
  diacritic: 0.1.3
  file_picker: 8.0.0
  go_router: ^15.1.2
  dio: ^5.4.0
  retrofit: ^4.1.0
  json_annotation: ^4.9.0
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: ^8.1.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true